version: '3'

services:
  etcd:
    image: quay.io/coreos/etcd:v3.5.12
    container_name: etc
    ports:
      - 2379:2379
      - 2380:2380
    command: /usr/local/bin/etc --config-file=/var/lib/etc/conf/etc.conf.yml
    volumes:
      - /root/components/etc/data:/var/etc
      - /root/components/etc/config/etc.conf.yml:/var/lib/etc/conf/etc.conf.yml
    restart: always
    networks:
      easy-chat:

  redis:
    image: redis:alpine3.18
    ports:
      - 16379:6379
    container_name: redis
    volumes:
      - /root/components/redis/data:/data
      - /root/components/redis/config/redis.conf:/usr/local/redis/config/redis.conf
    environment:
      TZ: Asia/Shanghai
    restart: always
    networks:
      easy-chat:
    command: redis-server /usr/local/redis/config/redis.conf --requirepass 12315.hys --appendonly yes

  mysql:
    image: mysql:5.7
    ports:
      - 13306:3306
    container_name: mysql
    volumes:
      - /root/components/mysql/data:/var/lib/mysql
      - /etc/localtime:/etc/localtime
    environment:
      MYSQL_ROOT_PASSWORD: 12315.hys
    restart: always
    networks:
      easy-chat:

  mongo:
    image: mongo:4.0
    container_name: mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: 12315.hys
    ports:
      - 47017:27017
    volumes:
      - /root/components/mongo/data:/data/db
      - /etc/localtime:/etc/localtime
    restart: always
    networks:
      easy-chat:

networks:
  easy-chat:
    driver: bridge