version: '3'

services:
  etcd:
    image: quay.io/coreos/etcd:v3.5.12
    container_name: etcd
    ports:
      - 2379:2379
      - 2380:2380
    command: /usr/local/bin/etcd --config-file=/var/lib/etcd/conf/etcd.conf.yml
    volumes:
      - /root/components/etcd/data:/var/etcd
      - /root/components/etcd/config/etcd.conf.yml:/var/lib/etcd/conf/etcd.conf.yml
    restart: always
    networks:
      easy-chat:

  redis:
    image: redis:alpine3.18
    ports:
      - 16379:6379
    container_name: redis
    volumes:
      - /root/components/redis/data:/data
      - /root/components/redis/config/redis.conf:/usr/local/redis/config/redis.conf
    environment:
      TZ: Asia/Shanghai
    restart: always
    networks:
      easy-chat:
    command: redis-server /usr/local/redis/config/redis.conf --requirepass 12315.hys --appendonly yes

  mysql:
    image: mysql:5.7
    ports:
      - 13306:3306
    container_name: mysql
    volumes:
      - /root/components/mysql/data:/var/lib/mysql
      - /etc/localtime:/etc/localtime
    environment:
      MYSQL_ROOT_PASSWORD: 12315.hys
    restart: always
    networks:
      easy-chat:

networks:
  easy-chat:
    driver: bridge