# 使用官方 Alpine 镜像
FROM alpine:latest

# 添加时区处理
RUN echo -e "https://mirrors.aliyun.com/alpine/v3.15/main\nhttps://mirrors.aliyun.com/alpine/v3.15/community" > /etc/apk/repositories && \
    apk update && \
    apk --no-cache add tzdata && \
    cp /usr/share/zoneinfo/Asia/Shanghai /etc/localtime && \
    echo "Asia/Shanghai" > /etc/timezone && \
    # 清理不需要的文件，减小镜像大小
    apk del tzdata

# 设置时区环境变量
ENV TZ=Asia/Shanghai

# 定义构建时的 ARG 变量
ARG SERVER_NAME=user
ARG SERVER_TYPE=rpc

# 设置运行时环境变量
ENV RUN_BIN bin/${SERVER_NAME}-${SERVER_TYPE}
ENV RUN_CONF /${SERVER_NAME}/conf/${SERVER_NAME}.yaml

# 创建目标目录
RUN mkdir /$SERVER_NAME && mkdir /$SERVER_NAME/bin && mkdir /$SERVER_NAME/conf

# 复制编译后的二进制文件和配置文件
# 注意：这些文件必须位于构建上下文内，不能超出 Docker build 目录
COPY deploy/dockerfile/bin/${SERVER_NAME}-${SERVER_TYPE} /$SERVER_NAME/bin/
COPY apps/${SERVER_NAME}/${SERVER_TYPE}/etc/${SERVER_NAME}.yaml /$SERVER_NAME/conf/

# 为二进制文件提供执行权限
RUN chmod +x /$SERVER_NAME/bin/${SERVER_NAME}-${SERVER_TYPE}

# 设置工作目录
WORKDIR /$SERVER_NAME

# 设置容器启动命令
ENTRYPOINT $RUN_BIN -f $RUN_CONF